server:
  port: 8080
spring:
   datasource:
     name: test
     username: root
     password: root123
     driver-class-name: com.mysql.cj.jdbc.Driver
     jdbcurl: mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #type-aliases-package: com.entity

